# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np 

In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_dimensional=np.array([1,2,3,4,5])
# Create a 2-dimensional NumPy array using np.array()
two_dimensional=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# Create a 3-dimensional Numpy array using np.array()
three_dimensional=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(one_dimensional.shape)
print(one_dimensional.ndim)
print(one_dimensional.dtype)
print(one_dimensional.size)
print(type(one_dimensional))

(5,)
1
int32
5
<class 'numpy.ndarray'>


In [4]:
# Attributes of 2-dimensional array
print(two_dimensional.shape)
print(two_dimensional.ndim)
print(two_dimensional.dtype)
print(two_dimensional.size)
print(type(two_dimensional))

(2, 5)
2
int32
10
<class 'numpy.ndarray'>


In [5]:
# Attributes of 3-dimensional array
print(three_dimensional.shape)
print(three_dimensional.ndim)
print(three_dimensional.dtype)
print(three_dimensional.size)
print(type(three_dimensional))

(1, 3, 3)
3
int32
9
<class 'numpy.ndarray'>


In [6]:
# Import pandas and create a DataFrame out of one
import pandas as pd
# of the arrays you've created
df=pd.DataFrame(two_dimensional)
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [7]:
# Create an array of shape (10, 2) with only ones
ones_array=np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array=np.zeros((7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
range_array=np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array=np.random.randint(0,10,size=(7,2))
random_array

array([[1, 9],
       [4, 0],
       [2, 0],
       [2, 8],
       [7, 5],
       [8, 1],
       [8, 7]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_array=np.random.random((3,5))
float_array

array([[0.26739639, 0.38458527, 0.91184644, 0.60495462, 0.79270557],
       [0.1305404 , 0.0948737 , 0.76566691, 0.72656256, 0.59338892],
       [0.65841859, 0.29420578, 0.74653939, 0.77324076, 0.20411907]])

In [12]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_2 = np.random.randint(0, 10, size=(4,6))
random_array_2


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_3=np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
print(np.unique(random_array_3))

[1 2 3 4 5 7 9]


In [14]:
# Find the 0'th index of the latest array you created
random_array_3[0]

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
# Get the first 2 rows of latest array you created
random_array_3[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_3[:2,:2]

array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_0_to_10=np.random.randint(0,10,size=(3,5))
ones_array_2=np.ones((3,5))
print(random_array_0_to_10)
print(ones_array_2)

[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
# Add the two arrays together
print(random_array_0_to_10 + ones_array_2)

[[ 7.  8.  3.  1.  4.]
 [ 2.  8.  4.  2.  6.]
 [ 6. 10.  4.  6.  2.]]


In [19]:
# Create another array of ones of shape (5, 3)
ones_array_3=np.ones((5,3))
ones_array_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Try add the array of ones and the other most recent array together
print(ones_array_3 + random_array_0_to_10)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)
ones_array_4=np.ones((3,5))
ones_array_4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Subtract the new array of ones from the other most recent array
print(random_array_0_to_10-ones_array_4)

[[ 5.  6.  1. -1.  2.]
 [ 0.  6.  2.  0.  4.]
 [ 4.  8.  2.  4.  0.]]


In [23]:
# Multiply the ones array with the latest array
print(random_array_0_to_10 * ones_array_4)

[[6. 7. 2. 0. 3.]
 [1. 7. 3. 1. 5.]
 [5. 9. 3. 5. 1.]]


In [24]:
# Take the latest array to the power of 2 using '**'
print(random_array_0_to_10**2)

[[36 49  4  0  9]
 [ 1 49  9  1 25]
 [25 81  9 25  1]]


In [25]:
# Do the same thing with np.square()
print(np.square(random_array_0_to_10))

[[36 49  4  0  9]
 [ 1 49  9  1 25]
 [25 81  9 25  1]]


In [26]:
# Find the mean of the latest array using np.mean()
print(np.mean(random_array_0_to_10))

3.8666666666666667


In [27]:
# Find the maximum of the latest array using np.max()
print(np.max(random_array_0_to_10))

9


In [28]:
# Find the minimum of the latest array using np.min()
print(np.min(random_array_0_to_10))

0


In [29]:
# Find the standard deviation of the latest array
print(np.std(random_array_0_to_10))

2.578543947441829


In [30]:
# Find the variance of the latest array
print(np.var(random_array_0_to_10))

6.648888888888889


In [31]:
# Reshape the latest array to (3, 5, 1)
print(random_array_0_to_10.reshape(3,5,1))

[[[6]
  [7]
  [2]
  [0]
  [3]]

 [[1]
  [7]
  [3]
  [1]
  [5]]

 [[5]
  [9]
  [3]
  [5]
  [1]]]


In [32]:
# Transpose the latest array
print(random_array_0_to_10.T)

[[6 1 5]
 [7 7 9]
 [2 3 3]
 [0 1 5]
 [3 5 1]]


What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_int_1=np.random.randint(0,10,size=(3,3))
random_int_2=np.random.randint(0,10,size=(3,2))

In [34]:
# Perform a dot product on the two newest arrays you created
print(np.dot(random_int_1,random_int_2))

[[ 88 117]
 [100 123]
 [ 89 127]]


In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_int_3=np.random.randint(0,10,size=(4,3))
random_int_4=np.random.randint(0,10,size=(4,3))
print(random_int_3)
print(random_int_4)

[[0 8 6]
 [8 7 0]
 [7 7 2]
 [0 7 2]]
[[2 0 4]
 [9 6 9]
 [8 6 8]
 [7 1 0]]


In [36]:
# Perform a dot product on the two newest arrays you created
print(np.dot(random_int_3,random_int_4))

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
print(np.dot(random_int_3.T,random_int_4))

[[128  90 128]
 [184  91 151]
 [ 42  14  40]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [40]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_int_5=np.random.randint(0,10,size=(3,3))
random_int_6=np.random.randint(0,10,size=(3,3))
random_int_5
random_int_6


array([[6, 3, 6],
       [2, 5, 1],
       [9, 8, 4]])

In [41]:
# Compare the two arrays with '>'
print(random_int_5 > random_int_6)

[[ True  True False]
 [ True False  True]
 [False False  True]]


What happens when you compare the arrays with `>`?

In [42]:
# Compare the two arrays with '>='
print(random_int_5 >= random_int_6)

[[ True  True False]
 [ True False  True]
 [False False  True]]


In [43]:
# Find which elements of the first array are greater than 7
print(random_int_5 > 7)

[[ True  True False]
 [False False False]
 [False False False]]


In [44]:
# Which parts of each array are equal? (try using '==')
print(random_int_5 == random_int_6)

[[False False False]
 [False False False]
 [False False False]]


In [45]:
# Sort one of the arrays you just created in ascending order
print(np.sort(random_int_5))

[[2 9 9]
 [0 3 6]
 [3 4 6]]


In [46]:
# Sort the indexes of one of the arrays you just created
print(np.argsort(random_int_5))

[[2 0 1]
 [1 2 0]
 [0 1 2]]


In [48]:
# Find the index with the maximum value in one of the arrays you've created
print(np.argmax(random_int_5))

0


In [49]:
# Find the index with the minimum value in one of the arrays you've created
print(np.argmin(random_int_5))

4


In [51]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print(np.argmax(random_int_5,axis=1))

[0 0 2]


In [52]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print(np.argmax(random_int_5,axis=0))

[0 0 2]


In [55]:
# Create an array of normally distributed random numbers
mean=0
std_dev=1
size_arr=5
normallay_array_dist=np.random.normal(mean,std_dev,size_arr)
normallay_array_dist

array([-0.25663018, -0.36782572,  1.27373362, -0.29195267, -2.65517605])

In [57]:
# Create an array with 10 evenly spaced numbers between 1 and 100
print(np.linspace(1,100,10))

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.